<a href="https://colab.research.google.com/github/41371231h-netizen/Programming-Language/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [89]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [90]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1XT78bjLWlX0FlME8q0i7wZcppPAp3fWycdE3-AN5JdQ/edit?usp=sharing')

In [91]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期    時間     分類     品項  金額 付款人  地點 支付方式   備註
0  2026-03-05  9:40  早餐三明治     50
1  2026-03-05  9:40  早餐三明治     50
2  2026-03-05  9:40         早餐三明治  50  本人       現金
3  2026-03-05  9:40         早餐三明治  50  本人  師大   現金  non
4  2026-03-05  9:40         早餐三明治  50  本人  師大   現金  non

In [92]:
import datetime

In [88]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH-MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H-%M')

item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
place=input("請輸入地點:  ")
way=input("請輸入付款方式:  ")
note=input("備註")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-05
請輸入時間 (格式：HH-MM): 10-15
請輸入品項: 日用
請輸入金額: 400
請輸入地點:  粽大
請輸入付款方式:  現金
備註777

In [93]:
date_str

'2026-03-05'

In [94]:
time_str

'10-15'

In [95]:
item

'日用'

In [96]:
amount

400.0

In [97]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': '早餐',
    '品項': item,
    '金額': amount,
    '付款人': 'ryan',
    '地點': '師大',
    '支付方式': way,
    '備註': note,
}])

# 先將空字串或空格替換為真正的 NaN，再統一填補為 0
df = pd.concat([df, new_data], ignore_index=True)
df = df.replace(r'^\s*$', np.nan, regex=True).fillna(0)
display(df)

            日期     時間     分類     品項     金額   付款人  地點 支付方式   備註
0   2026-03-05   9:40  早餐三明治     50      0     0   0    0    0
1   2026-03-05   9:40  早餐三明治     50      0     0   0    0    0
2   2026-03-05   9:40      0  早餐三明治     50    本人   0   現金    0
3   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
4   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
5   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
6   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
7   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
8   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
9   2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
10  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
11  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
12  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金   no
13  2026-03-05  10:03     早餐     早餐    500    本人  師大   現金   no
14  2006-03-05  10-10     早餐     午餐    600    本人  師大   現金   no
15  2026-03-05  10-15     早餐     日用  400.0  ryan  師大   現金  777

In [98]:
df

            日期     時間     分類     品項     金額   付款人  地點 支付方式   備註
0   2026-03-05   9:40  早餐三明治     50      0     0   0    0    0
1   2026-03-05   9:40  早餐三明治     50      0     0   0    0    0
2   2026-03-05   9:40      0  早餐三明治     50    本人   0   現金    0
3   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
4   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
5   2026-03-05   9:40      0  早餐三明治     50    本人  師大   現金  non
6   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
7   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
8   2026-03-05    957      0  早餐三明治     50    本人  師大   現金  non
9   2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
10  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
11  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金  non
12  2026-03-05    957     早餐  早餐三明治     50    本人  師大   現金   no
13  2026-03-05  10:03     早餐     早餐    500    本人  師大   現金   no
14  2006-03-05  10-10     早餐     午餐    600    本人  師大   現金   no
15  2026-03-05  10-15     早餐     日用  400.0  ryan  師大   現金  777

In [99]:
import pandas as pd
import numpy as np

# 確保所有欄位都有定義值，並處理缺失值
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': '早餐',
    '品項': item,
    '金額': amount,
    '付款人': '本人',
    '地點': place,
    '支付方式': way,
    '備註': note,
}])

# 強制將空欄位轉換為 0
new_data = new_data.replace(r'^\s*$', np.nan, regex=True).fillna(0)

# 將資料轉換為 list 格式
data_to_write = new_data.values.tolist()

# 取得工作表並寫入
try:
    worksheet = gsheets.worksheet('工作表1')
    worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
    print("資料已成功將空值與 nan 替換為 0 並寫入 Google 工作表！")
    display(new_data)
except Exception as e:
    print(f"寫入失敗：{e}")

資料已成功將空值與 nan 替換為 0 並寫入 Google 工作表！

           日期     時間  分類  品項     金額 付款人  地點 支付方式   備註
0  2026-03-05  10-15  早餐  日用  400.0  本人  粽大   現金  777